const GET_ALL_POST = 'BUTUN_POSTLARI_GETIR';
const GET_POST = 'POSTU_GETIR';
const CREATE_POST = 'POST_OLUSTUR';
const UPDATE_POST = 'POST_GUNCELLE';
const DELETE_POST = 'POST_SIL';
const LIKE_POST = 'POST_BEGENI';

export const actionTypes = { GET_ALL_POST, GET_POST, CREATE_POST, UPDATE_POST, DELETE_POST, LIKE_POST };
